((variance 1)
 (kernelSize 7)
 (thresholdMin 0.5)
 (thresholdMax 0.0399999991)
 (gradientParameters ((contrastType "Contrast")
   (format "Polar")
   (kernelType "Difference")
   (gradientKernelSize 3)
   (ogdVariance -1)))
 (noEdgeValue 0)
 (edgeValue 255))
